name: ua_pmlca
channels:
  - cmutel
  - conda-forge
dependencies:
  - brightway25_nosolver
  - jupyterlab
  - spyder
  - scikit-umfpack
  - ipywidgets=8.1.2=pyhd8ed1ab_0
  - black=24.2.0=py311h38be061_0
  - SALib
- pip:
  - jupyterlab-code-formatter==2.2.1
